name: Dockerized Test Workflow

on: [push]

jobs:
  build:
    name: test-code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: continuumio/anaconda3:2022.05
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Test code in Docker container
        run: |
          pip install tabulate
          pytest --verbose test_myruleminer.py
      - name: Pylint code in Docker container
        if: always()
        run: |
          pylint -v $(git ls-files "*.py") --exit-zero # always return 0 (non-error) so pylint warnings/errors do not error this step out